kind: pipeline
name: default

steps:
  - name: build
    image: node:carbon-alpine
    commands:
      - npm install
      - npm run build

  - name: publish_docker_master
    image: plugins/docker
    settings:
      registry: docker.cloud.neocodenetworks.org
      repo: docker.cloud.neocodenetworks.org/mue/telnet-bridge
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - master
    when:
      branch: master
      event: push

  - name: publish_docker_branch
    image: plugins/docker
    settings:
      registry: docker.cloud.neocodenetworks.org
      repo: docker.cloud.neocodenetworks.org/mue/telnet-bridge
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: ${DRONE_BRANCH}
    when:
      branch:
        exclude: master
      event: push

  - name: publish_docker_tag
    image: plugins/docker
    settings:
      registry: docker.cloud.neocodenetworks.org
      repo: docker.cloud.neocodenetworks.org/mue/telnet-bridge
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: ${DRONE_TAG}
    when:
      event: tag

  - name: publish_docker_to_prod
    image: plugins/docker
    settings:
      registry: docker.cloud.neocodenetworks.org
      repo: docker.cloud.neocodenetworks.org/mue/telnet-bridge
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: prod
    when:
      target: production

  - name: notify_neopush
    image: docker.cloud.neocodenetworks.org/neopush/drone
    pull: always
    err_ignore: true
    settings:
      neopush_api_key:
        from_secret: neopush_api_key

---
kind: secret
name: docker_username
get:
  path: commonsecrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: commonsecrets
  name: docker_password
---
kind: secret
name: neopush_api_key
get:
  path: commonsecrets
  name: neopush_api_key
