name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Build
        run: |
          npm install
          npm run build
      - name: Publish to Registry
        if: success() && github.event_name != 'pull_request'
        uses: HurricanKai/Publish-Docker-Github-Action@1.12.2
        with:
          name: docker.pkg.github.com/${{ github.repository }}/mue-telnet-bridge
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
